version: "3.9"
name: hello-django-dev
services:
  web:
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../..:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poll
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pgdata:
    name: poll-volume