image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      createdb poll; :
    command: docker/dev/start.sh
  - init: python manage.py tailwind install
    command: python manage.py tailwind start

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
    name: Website
    description: Website Preview
