image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      createdb poll
      cp .env_example .env
    command: docker/dev/start.sh

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
    name: Website
    description: Website Preview
