image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      createdb poll
      pip install --use-pep517 --no-cache-dir -r requirements.txt
    command: docker/dev/start.sh

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
    name: Website
    description: Website Preview
