image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      python manage.py tailwind install
      python manage.py tailwind build
      gp sync-done tailwind
    command: python manage.py tailwind start
  - init: |
      createdb poll; :
      gp sync-await tailwind
    command: docker/dev/start.sh

# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
    name: Website
    description: Website Preview
