version: "3.9"
name: hello-django-prod
services:
  web:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    command: uvicorn mysite.asgi:application --host 0.0.0.0
    ports:
      - 80:8000
